= Asciidoc Presentation

This project is a quick start project for using Asciidoctor with
the Reveal.js plugin. It also utilizes Decktape.js to render the
slides to a pdf.

== Using

This project relies on bundler (the standard dependency manager in ruby).

`gem install bundler`

=== Setup
* `bundle install`
* without Decktape.js: `bundle exec rake init`
* with Decktape.js: `bundle exec rake init-all`

If you want to use Decktape.js you need npm to be installed and accessible from
your terminal.

=== Build

* `bundle exec rake build`
** this will build only the Reveal.js version
* `bundle exec rake build-all`
** this will build pdf, html, slides-pdf, reveal.js

=== Run

* to start the presentation simply open the file `out/revealjs/project_name.html`

== Settings

All relevant settings are found in `config.rb`.

== Standard directory layout

[source]
----
src/
  -- asciidoc/
  -- resources/
     -- images/
     -- videos/
     -- generated/
     -- pdf_images_dir/
out/
  -- html/
  -- pdf/
  -- revealjs/
  -- slides-pdf/
----

All files under _resources/images_, _resources/videos and _resources/generated_ are copied to
_{reveal-js-out-dir}/static_ and _src/resources/pdf_images_dir_. So you should avoid having conflicting names (i.e. files that have
the same name).

_src/resources/pdf_images_dir_ is needed because asciidoctor-pdf can not look in multiple
directories for resources. This directory is on gitignore.

In _resources/generated_ are all generated files (e.g. pictures from plantuml embedded in asciidoc).
This directory is also on gitignore.

== Gradle / Java

On branch `gradle-java` you will find a quick start project for using the
presentation project with java source code.

Before you start, you should execute `./gradlew initAll` (or `bundle install && bundle exec rake init-all`).

=== Compile Java and Reveal.js

`./gradlew build`

* the Reveal.js task will run after the build task

=== Build all output formats

`./gradlew buildAll`

=== Change project name

`settings.gradle` contains the project name.

== Custom Macros

You can find example macros under `build-scripts/extensions.rb`. The macros in action
can be seen in the presentation itself.

=== Added macro

==== Fragments

You can tag whole blocks as a fragment with the following:

[source]
----
fragment::begin[]
Stuff, that should be revealed during presentation.
fragment::end[]
----

In default asciidoctor revealjs, you can only tag lists with [%step] to make each bullet an own fragment.

==== Speaker Only Notes

If you want to add speaker notes that should *not* be included in the other output formats:

[source]
----
speaker-only::begin[]
Your notes...
speaker-only::end[]
----

This will transform to `[NOTE.speaker]` for backend `revealjs` and to a block comment for
all other backends (and thus not included in the output).

==== Slide break

If you want to have a new slide without a title:

[source]
----
slidebreak::[]
----

This will be transformed to `=== !` for backend `revealjs` and for all other backends it
will be dropped.

==== Slides only

If you want to have some things only on the slides (and slides pdf) you can use the following:

[source]
----
slides-only::begin[]
Slides only stuff
slides-only::end[]
----
