= Asciidoc Presentation

This project is a quick start project for using Asciidoctor with
the Reveal.js plugin. It also utilizes Decktape.js to render the
slides to a pdf.

== Using

This project relies on bundler (the standard dependency manager in ruby).

`gem install bundler`

=== Setup
* `bundle install`
* without Decktape.js: `bundle exec rake init`
* with Decktape.js: `bundle exec rake init-all`

If you want to use Decktape.js you need npm to be installed and accessible from
your terminal.

=== Build

* `bundle exec rake build`
** this will build only the Reveal.js version
* `bundle exec rake build-all`
** this will build pdf, html, slides-pdf, reveal.js

=== Run

* to start the presentation simply open the file `out/revealjs/project_name.html`

== Settings

All relevant settings are found in `config.rb`.

== Standard directory layout

[source]
----
src/
  -- asciidoc/
  -- resources/
     -- images/
     -- videos/
out/
  -- html/
  -- pdf/
  -- revealjs/
  -- slides-pdf/
----

== Gradle / Java

On branch `gradle-java` you will find a quick start project for using the
presentation project with java source code.

=== Compile Java and Reveal.js

`./gradlew build`

* the Reveal.js task will run after the build task

=== Build all output formats

`./gradlew buildAll`

=== Change project name

`settings.gradle` contains the project name.

== Custom Macros

You can find example macros under `build-scripts/extensions.rb`. The macros in action
can be seen in the presentation itself.

=== Added macros

There is already a custom preprocessing macro for having the speaker notes only on the
speaker notes page:

[source]
----
speaker-only::begin[]
Your notes...
speaker-only::end[]
----

This will transform to `[NOTE.speaker]` for backend `revealjs` and to a block comment for
all other backends (and thus not included in the output).
